### ISSUE TITLE
Is train_mrcnn.py in another repository?

### ISSUE THREAD

**Issue by miaojiang1987** [shtamura/glcic#1]
Dear Shtamura-san,

Thank you for implementing the paper with Keras. I am trying to implement this, I have a question. In the instruction, there is:
python3 train_mrcnn.py --weights_path ./model/glcic-latest-stage1-xx.h5 --data_path /path/to/dataset --stage 2

I am wondering is trin_mrcnn.py in another repository?

Best,
Miao

**Comment by shtamura** [comment]
Dear Miao-san

Thank you for your advice. 
As you said, "train_mrcnn.py" is a file of another repository. Correctly it is "train.py". 
I fixed it.

Thank you.
